package ar.com.survey.model;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;

import ar.com.survey.questions.fields.Field;

/**
 * 
 */
public abstract class QuestionAbstract implements Serializable {

	private static final long serialVersionUID = 1L;
	
	// ------------- To be implemented by POJO generated by H3

    abstract long getId();   
    abstract void setId(long id);
    abstract int getVersion();
    abstract void setVersion(int version);
    
    
    abstract public String getTitle();
    abstract public void setTitle(String title);
    abstract public String getDescription();   
    abstract public void setDescription(String description);
    
    abstract  public Section getSection();   
    abstract  public void setSection(Section section);
    
//    abstract protected int getColumnCount();   
//    abstract protected void setColumnCount(int columns);    
//    abstract protected int getRowCount();
//    abstract protected void setRowCount(int rows);
  
    
    abstract protected List<String> getColumnTitles();   
    abstract protected void setColumnTitles(List<String> columnTitles);
    
    abstract protected List<String> getRowTitles();   
    abstract protected void setRowTitles(List<String> rowTitles);

    abstract protected Collection<Field> getFields();   
    abstract protected void setFields(Collection<Field> fields);
    


	public int getPosition() {
		return this.getSection().getQuestions().indexOf(this);
	}
	protected Field getFieldAt(int x, int y) {
		for (Field f : this.getFields()) {
			if ((f.getXpos() == x) && (f.getYpos() == y)) {
				return f;
			}
		}
		return null;
	}
	final public void addField(Field f) {
		Field existentField = this.getFieldAt(f.getXpos(), f.getYpos());
		if (existentField != null) {
			this.getFields().remove(existentField);
		}
		this.getFields().add(f);
	}
}
